version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "charon"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: .
    binary: charon
    ldflags:
      - -s -w -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.buildDate={{.Date}}'

  - id: "worker"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/worker/
    binary: worker
    ldflags:
      - -s -w -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.buildDate={{.Date}}'

archives:
  - id: "charon"
    builds:
      - charon
      - worker
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - .env.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
